// <auto-generated />
using CarWorkshopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarWorkshopAPI.Migrations
{
    [DbContext(typeof(CarWorkshopDbContext))]
    partial class CarWorkshopAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarWorkshopAPI.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 100,
                            Description = "Wymiana oleju",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 300,
                            Description = "Wymiana Filtrów",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cost = 50,
                            Description = "Zmiana opon",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cost = 400,
                            Description = "Wymiana tarcz hamulcowych",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Cost = 200,
                            Description = "Wymiana klockow hamulcowych",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cost = 1500,
                            Description = "Wymiana glowicy",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 7,
                            Cost = 300,
                            Description = "Wymiana panewek",
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarWorkshopAPI.Models.TechnicalPassport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("TechnicalPassports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OwnerName = "Jakub",
                            RegistrationNumber = "GD 9321",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            OwnerName = "Marcin",
                            RegistrationNumber = "WA 1234",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            OwnerName = "Jan",
                            RegistrationNumber = "KK 2244",
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarWorkshopAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Model = "F10",
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            Model = "E30",
                            Year = 1987
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mercedes",
                            Model = "W123",
                            Year = 1982
                        });
                });

            modelBuilder.Entity("CarWorkshopAPI.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("CarWorkshopAPI.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarWorkshopAPI.Models.TechnicalPassport", b =>
                {
                    b.HasOne("CarWorkshopAPI.Models.Vehicle", "Vehicle")
                        .WithOne("TechnicalPassport")
                        .HasForeignKey("CarWorkshopAPI.Models.TechnicalPassport", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarWorkshopAPI.Models.Vehicle", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("TechnicalPassport")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
